// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    int32
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
