openapi: "3.0.0"
info:
  version: 1.0.0
  title: DB Practice
  description: A test swagger for interacting wiht a database
  contact:
    name: Mike Schon
    email: mschon314@gmail.com
servers:
  - url: localhost:8080/v1
paths:
  /users:
    get:
      description: |
        Returns all users from the system
      operationId: findUsers
      parameters:
        - name: username
          in: query
          description: username to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - type: object
          required:
            - user_id
          properties:
            user_id:
              type: integer
              format: int32
            created_at:
              type: string
            updated_at:
              type: string

    NewUser:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
